### ISSUE TITLE
USB - UART bridge

### ISSUE THREAD

**Issue by davidthings** [stacksmashing/pico-serprog#7]
Does anyone ask for UART passthrough to be added to the functionality of pico-serprog?

A use case is: programming an FPGA, then switching to talking to it via UART on TX and RX lines.  It would be very nice to not have to use a whole separate device.  Ideally there should be dual serial ports - one for serprog and the other for the uart so the code connected to the uart can say connected during the flashing process.

Is this a feature that could be added to pico-serprog, or is this better done as a fork and do something new project?

**Comment by davidthings** [comment]
(I'm offering to do either)

**Comment by nezza** [comment]
I think this would be a cool feature, feel free to add!
